[package]
name = "meteostation-pi"
version = "0.1.0"
authors = ["Stas Rudakou <stas@garage22.net>"]

[dependencies]
dht22_pi = "0.1.0"
env_logger = "0.4.3"
hyper = "0.10.12"
lazy_static = "0.2"
log = "0.3"
prometheus = "0.2.8"
